spring:
  security:
    oauth2:
      client:
        registration:
          authorizationserver:
            client-id: client-for-server
            client-secret: client-for-server
            provider: authorizationserver
            client-name: "使用自定义授权服务登录"
            authorization-grant-type: authorization_code
            client-authentication-method: basic
            scope: profile,email,phone
            redirect-uri-template: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          authorizationserver:
            authorization-uri: http://localhost:9999/oauth/authorize
            token-uri: http://localhost:9999/oauth/token
            user-info-uri: http://localhost:9999/me
            user-name-attribute: "name"
